services:
  - type: web
    name: escola-digital
    env: python
    plan: free
    region: oregon  # ou 'frankfurt' se quiser hospedar na Europa

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn main:app

    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_SENHA
        sync: false
      - key: SECRET_KEY
        sync: false

    autoDeploy: true
